# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uSax6G1FABWvAxgkokKxTJokdRb2mnY
"""

# Atividade 1
resposta = input("Deseja continuar no sistema? (Sim/Não): ")

# O método .lower() converte qualquer variação (SIM, Sim, sIm) para "sim"
if resposta.lower() == "sim":
    print("Continuando...")
else:
    print("Encerrando...")

# Atividade 2
uf = input("Digite a sigla do seu estado (ex: sp, rj, mg): ")

# O método .upper() garante que a saída fique sempre em letras maiúsculas
uf_padronizada = uf.upper()
print(f"Estado cadastrado: {uf_padronizada}")

# Atividade 3
CUPOM_VALIDO = "DESCONTO10"

cupom_usuario = input("Digite o seu cupom promocional: ")

# Converte a entrada do usuário para maiúsculas antes de validar
if cupom_usuario.upper() == CUPOM_VALIDO:
    print("Cupom aplicado com sucesso!")
else:
    print("Cupom inválido.")

# Atividade 4
nome = input("Digite o seu primeiro nome: ")

# Remove espaços acidentais no início e no fim
nome_limpo = nome.strip()

print(f"Nome limpo: {nome_limpo}")
print(f"Quantidade de caracteres: {len(nome_limpo)}")

# Atividade 5
email = input("Digite o seu e-mail: ")

# Remove os espaços e verifica se o campo ficou vazio
if email.strip() == "":
    print("Erro: O campo e-mail não pode ficar em branco!")
else:
    print("E-mail cadastrado!")

# Atividade 6
USUARIO_CORRETO = "aluno@escola.com"

login = input("Digite seu login: ")

# Trata a entrada removendo espaços (strip) e padronizando em minúsculas (lower)
login_tratado = login.strip().lower()

if login_tratado == USUARIO_CORRETO:
    print("Login realizado com sucesso!")
else:
    print("Falha no login: Usuário incorreto.")